# random seed
seed: 0

# data_args
dataset: "mnist"
data_dir: "../data"

# train args:
device: "cuda:0"
batch_size: 512
learning_rate: 0.01
weight_decay: 0.00
train_epochs: 10
sched_gamma: 0.999

# model params
img_height: 28
img_width: 28
hidden_dim: 128
latent_dim: 32
n_layers: 3
layernorm: false

save_results_path: "../results/notebook_train_results.pkl"
save_model_path: "../checkpoints/notebook_autoencoder_model.pth"
loss_curve_path: "../figs/notebook_mnist_loss_curve.png"
reconstruction_path: "../figs/notebook_mnist_reconstruction.png"